# Generated by Django 3.2.3 on 2021-06-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
