# Generated by Django 3.2.3 on 2021-06-14 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='submission',
        ),
    ]
